checkpoint_frequency: null
data_dir: data/
dataset: WikiText2
epochs: 10
learning_rate: 0.1
model_dir: weights/cbow-128-0.1
model_name: cbow
optimizer: Adam
shuffle: true
train_batch_size: 128
train_steps: null
val_batch_size: 96
val_steps: null
