checkpoint_frequency: null
data_dir: data/
dataset: WikiText2
epochs: 10
learning_rate: 0.025
model_dir: weights/cbow-96-0.025
model_name: cbow
optimizer: Adam
shuffle: true
train_batch_size: 96
train_steps: null
val_batch_size: 96
val_steps: null
